version: '2'
networks:
  project:
    external: false
volumes:
  mysql_data:
  composer_home:
services:
  mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - project
    volumes:
      - ./mysql/zz.cnf:/etc/mysql/conf.d/zz.cnf
      - ./mysql/init.d/:/docker-entrypoint-initdb.d/
      - mysql_data:/var/lib/mysql
  php-fpm:
    build:
      context: ./php-fpm
      args:
        X_GID: ${X_GID}
        X_UID: ${X_UID}
    networks:
      - project
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ..:/project
      - composer_home:/tmp/composer
  nginx:
    image: nginx:1.14.2-alpine
    command: /bin/sh -c "envsubst '$$X_DOMAIN' < /etc/nginx/project/sites.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      X_DOMAIN: ${X_DOMAIN}
    networks:
      - project
    volumes:
      - ./nginx:/etc/nginx/project
      - ../app/web:/project/app/web
  fluentd-forwarder:
    image: fluentd:v1.6-1
    networks:
      - project
    volumes:
      - ./fluentd-forwarder/fluentd.conf:/fluentd/etc/fluent.conf
    depends_on:
      - fluentd-sink
  fluentd-sink:
    build:
      context: ./fluentd-sink
    networks:
      - project
    volumes:
      - ./fluentd-sink/fluentd.conf:/fluentd/etc/fluent.conf


